export const events: Array<{ id: string, name: string, multiplicator: number, rounds: number, sortByAverage: boolean }> =
  [
    { id: "333", name: "Cubo 3x3x3", multiplicator: 2, rounds: 3, sortByAverage: true },
    { id: "222", name: "Cubo 2x2x2", multiplicator: 1.5, rounds: 3, sortByAverage: true },
    { id: "444", name: "Cubo 4x4x4", multiplicator: 1.5, rounds: 2, sortByAverage: true },
    { id: "555", name: "Cubo 5x5x5", multiplicator: 1.25, rounds: 1, sortByAverage: true },
    { id: "666", name: "Cubo 6x6x6", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "777", name: "Cubo 7x7x7", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "333bf", name: "3x3x3 BLD", multiplicator: 1.5, rounds: 2, sortByAverage: false },
    { id: "333fm", name: "3x3x3 FMC", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "333oh", name: "3x3x3 OH", multiplicator: 1.25, rounds: 2, sortByAverage: true },
    { id: "minx", name: "Megaminx", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "pyram", name: "Pyraminx", multiplicator: 1.25, rounds: 2, sortByAverage: true },
    { id: "clock", name: "Clock", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "skewb", name: "Skewb", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "sq1", name: "Square-1", multiplicator: 1, rounds: 1, sortByAverage: true },
    { id: "444bf", name: "4x4x4 BLD", multiplicator: 0.75, rounds: 1, sortByAverage: false },
    { id: "555bf", name: "5x5x5 BLD", multiplicator: 0.75, rounds: 1, sortByAverage: false },
    { id: "333mbf", name: "Multi BLD", multiplicator: 0.75, rounds: 1, sortByAverage: false },
  ];
