export const events: { id: string, name: string, cubecomps_id: number }[] =
    [
        { id: "333", name: "Cubo 3x3x3", cubecomps_id: 1 },
        { id: "222", name: "Cubo 2x2x2", cubecomps_id: 2 },
        { id: "444", name: "Cubo 4x4x4", cubecomps_id: 3 },
        { id: "555", name: "Cubo 5x5x5", cubecomps_id: 4 },
        { id: "666", name: "Cubo 6x6x6", cubecomps_id: 5 },
        { id: "777", name: "Cubo 7x7x7", cubecomps_id: 6 },
        { id: "333bf", name: "3x3x3 BLD", cubecomps_id: 16 },
        { id: "333fm", name: "3x3x3 FMC", cubecomps_id: 15 },
        { id: "333oh", name: "3x3x3 OH", cubecomps_id: 13 },
        { id: "minx", name: "Megaminx", cubecomps_id: 10 },
        { id: "pyram", name: "Pyraminx", cubecomps_id: 11 },
        { id: "clock", name: "Clock", cubecomps_id: 7 },
        { id: "skwb", name: "Skewb", cubecomps_id: 20 },
        { id: "sq1", name: "Square-1", cubecomps_id: 12 },
        { id: "444bf", name: "4x4x4 BLD", cubecomps_id: 17 },
        { id: "555bf", name: "5x5x5 BLD", cubecomps_id: 18 },
        { id: "333mbf", name: "Multi BLD", cubecomps_id: 19 },
    ];