export const events: Array<{ id: string, name: string, cubecomps_id: number, multiplicator: number, rounds: number, sortByAverage: boolean}> =
    [
        { id: "333", name: "Cubo 3x3x3", cubecomps_id: 1, multiplicator: 2, rounds: 3 , sortByAverage: true},
        { id: "222", name: "Cubo 2x2x2", cubecomps_id: 2, multiplicator: 1.5, rounds: 3 , sortByAverage: true},
        { id: "444", name: "Cubo 4x4x4", cubecomps_id: 3, multiplicator: 1.5, rounds: 2 , sortByAverage: true},
        { id: "555", name: "Cubo 5x5x5", cubecomps_id: 4, multiplicator: 1.25, rounds: 1 , sortByAverage: true},
        { id: "666", name: "Cubo 6x6x6", cubecomps_id: 5, multiplicator: 1, rounds: 1 , sortByAverage: true},
        { id: "777", name: "Cubo 7x7x7", cubecomps_id: 6, multiplicator: 1, rounds: 1 , sortByAverage: true},
      //  { id: "333bf", name: "3x3x3 BLD", cubecomps_id: 16, multiplicator: 1.5, rounds: 2 , sortByAverage: false},
      //  { id: "333fm", name: "3x3x3 FMC", cubecomps_id: 15, multiplicator: 1, rounds: 1 , sortByAverage: true},
      //  { id: "333oh", name: "3x3x3 OH", cubecomps_id: 13, multiplicator: 1.25, rounds: 2 , sortByAverage: true},
        { id: "minx", name: "Megaminx", cubecomps_id: 10, multiplicator: 1, rounds: 1 , sortByAverage: true},
      //  { id: "pyram", name: "Pyraminx", cubecomps_id: 11, multiplicator: 1.25, rounds: 2 , sortByAverage: true},
       // { id: "clock", name: "Clock", cubecomps_id: 7, multiplicator: 1, rounds: 1 , sortByAverage: true},
       // { id: "skewb", name: "Skewb", cubecomps_id: 20, multiplicator: 1, rounds: 1 , sortByAverage: true},
        { id: "sq1", name: "Square-1", cubecomps_id: 12, multiplicator: 1, rounds: 1 , sortByAverage: true},
       // { id: "444bf", name: "4x4x4 BLD", cubecomps_id: 17, multiplicator: 0.75, rounds: 1 , sortByAverage: false},
       // { id: "555bf", name: "5x5x5 BLD", cubecomps_id: 18, multiplicator: 0.75, rounds: 1 , sortByAverage: false},
       // { id: "333mbf", name: "Multi BLD", cubecomps_id: 19, multiplicator: 0.75, rounds: 1 , sortByAverage: false},
    ];
